@startuml
'https://plantuml.com/use-case-diagram

left to right direction
:PO/SM/TeamMember: as User
rectangle System{
    usecase "Insert Project Code" as US1
    usecase "Verify Project Code" as US2
    usecase "Display Project error" as US3
    usecase "Get Product Backlog" as US4
    usecase "Get Product Backlog" sorted by Priority" as US5
}
User --> US1
US1 .right.> US2 : include
US3 .up.> US1 : extend
User --> US4
US4 <-down- US5
@enduml