@startuml
'https://plantuml.com/class-diagram

class Project

class Project {
Code
Name
Description
Number of planned sprints
Status
Start date
End date
Budget
Sprint default duration
Sprint list
}

class User {
User ID
Name
Function
Photo
Password
Email
Status
}

User "1" -right- "1" Project: project manager edit static information

@enduml