@startuml
'https://plantuml.com/use-case-diagram

'https://plantuml.com/use-case-diagram

left to right direction
:Project Manager: as User
rectangle System{

    usecase "Get project by inserting the project code" as US1
    usecase "Edit some project information" as US2
}

User --> US1
User --> US2

@enduml