@startuml
'https://plantuml.com/class-diagram

skinparam linetype ortho
package Infrastructure{
class CreateProjectRoute
interface IDBDriver
}


package InterfaceAdapters{
interface IControllerProject
class CreateProjectController
class RepoProject
}



package ApplicationServices/UseCaseServices{
interface IAppServiceProject
interface IRepoProject
class AppServiceProject
interface IProjectFactory
class ProjectFactory
}

package Entities/Core/Domain{
class Project
}




CreateProjectRoute ..down.> IControllerProject
IControllerProject  <|.. CreateProjectController

CreateProjectController ..> IAppServiceProject
IAppServiceProject <|.. AppServiceProject
ProjectFactory ..|> IProjectFactory
AppServiceProject .left.> IProjectFactory


AppServiceProject ....> Project

AppServiceProject .right..> IRepoProject
IRepoProject <|.up. RepoProject

RepoProject ...> IDBDriver


@enduml