@startuml
'https://plantuml.com/class-diagram

left to right direction
package UI{
class CreateProjectUI{
}
}
package Controller {
class CreateProjectController{
+createProject(projectDTO)
}
}
package Model {
class DataManagement{
-projectStore:ProjectStore
+getProjectStore()

}
class ProjectStore{
+createProject(projectDTO))

}
interface ProjectFactory{
createProject()

class ProjectFactoryOne
}
class Project {
-String code;
-String name;
-String description;
-double budget;
-Typology typology;
-ProductBacklog productBacklog;
-Customer customer;
-List<Sprint> sprintList;
-int defaultSprintDuration;
-int numberOfPlannedSprints;
-String status;
-Resource productOwner;
-ResourceUser projectManager;
-ResourceUser scrumMaster;
-List<ResourceUser> projectTeam;
-LocalDate startDate;
-LocalDate endDate;

}
class ProductBacklog{
}
}


CreateProjectUI ..> CreateProjectController
CreateProjectController ..> "dataManagement"DataManagement
DataManagement -- ProjectStore
ProjectFactory <.. ProjectStore
ProjectFactory <|.. ProjectFactoryOne
CreateProjectController ....>  "projectStore"ProjectStore
ProjectStore o-- "project" Project
Project o--- "productBacklog" ProductBacklog



@enduml