@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Director" as director
participant "System" as system


director --> system:I want to create a project.
director <-- system: Request mandatory data.
director --> system:Insert data.
director <-- system:Successful


@enduml