@startuml
'https://plantuml.com/sequence-diagram

autonumber


Actor "PO/SM/TeamMember" as user
participant " : GetProductBacklogRoute" as route
participant " userStoryController : UserStoryController" as getProductBacklogCTRL
participant " productBacklogService: ProductBacklogService" as pblService
participant " projectCode: ProjectCode" as code
participant " projectRepository : ProjectRepository" as projectRepo
participant " userStoryRepository : UserStoryRepository" as usRepo
participant " userStoryDomainDTOAssembler : UserStoryDomainDTOAssembler" as assembler
participant " userStoryDTO : UserStoryDTO " as usDTO

'::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::'
user -> route : I want to get the Product Backlog of a project
activate user
activate route
route -> user : Request data (project ID)
deactivate user
user -> route : Insert requested data (json)
activate user
route -> getProductBacklogCTRL : getProductBacklogSortedByPriority(String projectCode)
activate getProductBacklogCTRL
getProductBacklogCTRL --> getProductBacklogCTRL : validate(json)
getProductBacklogCTRL -> pblService : GetProductBacklogSortedByPriority(String projectCode)
activate pblService
pblService --> code **: new ProjectCode(projectCode)
pblService -> projectRepo : existsProjectByProjectCode(projectCode)
activate projectRepo
projectRepo  --> pblService : true
deactivate projectRepo
group ForEach [known project]
pblService -> usRepo : FindAllByProjectCode(projectCode)
activate usRepo
usRepo --> pblService : (productBacklog)
deactivate usRepo
end
pblService --> pblService : sortProductBacklogByPriority(productBacklog)
group ForEach [userStory]
pblService -> assembler : sortedProductBacklog
activate assembler
assembler -> usDTO **: fromDomainToDTO(userStory)
assembler --> pblService : sortedProductBacklogDTO
deactivate assembler
end
pblService --> getProductBacklogCTRL : sortedProductBacklogDTO
deactivate pblService
getProductBacklogCTRL --> route : sortedProductBacklogDTO
deactivate getProductBacklogCTRL
route --> user : sortedProductBacklogJSON
deactivate user
deactivate route

@enduml