@startuml
'https://plantuml.com/sequence-diagram

autonumber
autoactivate on

Actor "PO/SM/TeamMember" as PO_SM_TeamMember
Participant "GetProductBacklogSortedByPriorityUI" as GetProductBacklogSortedByPriorityUI
Participant ":GetProductBacklogSortedByPriorityController" as getProductBacklogSortedByPriorityController
Participant ":DataManagement" as DataManagement
Participant "projectStore : ProjectStore" as ProjectStore
Participant "project : Project" as Project
Participant "productBacklog : ProductBacklog" as ProductBacklog

PO_SM_TeamMember -> GetProductBacklogSortedByPriorityUI: I want to to get the Product Backlog of a project
GetProductBacklogSortedByPriorityUI --> PO_SM_TeamMember: Request Project code

PO_SM_TeamMember -> GetProductBacklogSortedByPriorityUI: Type requested project code

GetProductBacklogSortedByPriorityUI -> getProductBacklogSortedByPriorityController: getProductBacklog(projectCode)

getProductBacklogSortedByPriorityController -> DataManagement: getProjectStore() : projectStore

DataManagement --> getProductBacklogSortedByPriorityController: projectStore

group loop [For each know project]
    getProductBacklogSortedByPriorityController -> ProjectStore : getProjectByCode(projectCode) : project
    ProjectStore --> getProductBacklogSortedByPriorityController: showProjectCode
    alt if projectCode == showProjectCode
        getProductBacklogSortedByPriorityController -> Project: getProductBacklog() : productBacklog
       Project -> ProductBacklog: getProductBacklog()
    end
end

ProductBacklog --> getProductBacklogSortedByPriorityController: productBacklog
getProductBacklogSortedByPriorityController --> GetProductBacklogSortedByPriorityUI: productBacklog
GetProductBacklogSortedByPriorityUI --> PO_SM_TeamMember: Show Product Backlog

PO_SM_TeamMember -> GetProductBacklogSortedByPriorityUI: I want to order the given ProductBacklog by Priority
GetProductBacklogSortedByPriorityUI -> getProductBacklogSortedByPriorityController: getProductBacklogSortedByPriority(projectCode))
getProductBacklogSortedByPriorityController -> Project: getProductBacklog()

Project -> ProductBacklog: getProductBacklog()
ProductBacklog -> ProductBacklog: sortProductBacklogByPriority
ProductBacklog --> Project: showSortedProductBacklog
Project --> getProductBacklogSortedByPriorityController: showSortedProductBacklog
getProductBacklogSortedByPriorityController --> GetProductBacklogSortedByPriorityUI: showSortedProductBacklog
GetProductBacklogSortedByPriorityUI --> PO_SM_TeamMember: Show Product Backlog sorted by priority







@enduml