@startuml
'https://plantuml.com/use-case-diagram

header
Use Case Diagram of US019
endheader

center footer US 019 - As Team Member, I want to estimate the effort of a user story.



left to right direction
:Team member: as User
package System{
    usecase "Wanto to estimate the effort of a user story" as US1
    usecase "enum of effort" as US2
    usecase "List of userStories" as US3
    usecase "Insert the user story ID" as US4
    usecase "Insert the effort " as US5
    usecase "Associate the effort to the user Story" as US6
User --> US1
US1 ..> US3
US1 ..> US2
User --> US4
User --> US5
User --> US6

@enduml