@startuml
autonumber
actor TeamMember
participant UI
participant TeamMemberController
participant DataManagement
participant ProjectStore
participant project
participant Sprint
participant SprintBacklog

TeamMember -> UI : I want to estimate the effort of a user story
UI -> TeamMemberController : setEffortToUserStory()
TeamMemberController -> DataManagement : getProjectStore()
TeamMemberController <-- DataManagement : projectStore
TeamMemberController -> ProjectStore : : getProjectByCode(codeProject)
TeamMemberController <-- ProjectStore : project
TeamMemberController ->  project : : getSprintById(sprintId)
TeamMemberController <-- project : sprint
TeamMemberController -> Sprint : : getSprintBacklog()
TeamMemberController <-- Sprint : sprintBacklog
TeamMemberController -> SprintBacklog : : setEffortToUserStory(userStory, effort)
SprintBacklog -> UserStory : : setEffort(effort)

@enduml