@startuml
'https://plantuml.com/class-diagram

class GetListUI #line:blue;back:lightblue
class GetUserAccountAndStatusListController
class DataManagement
class UserStore
class UserMapper
class UserDTO
class User

class GetUserAccountAndStatusListController #line:blue;back:lightblue{
DataManagement dataManagement
UserMapper userMapper
+getUsersList()
+getUserDtoList()
}

class DataManagement #line:blue;back:lightblue{
+getUserStore()
}

class UserStore #line:blue;back:lightblue{
+getUserList() : arraylist
}

class UserMapper #line:blue;back:lightblue{
+userDTO()
+listDto() : arraylist
}

class User #line:blue;back:lightblue{
-String name
-String function
-String email
-String password
-String photo
-int userID
-boolean isUserAccountActivated
+getUserid() : int
+getNameId() : String
+getUserStatus() : boolean
}

class UserDTO #line:blue;back:lightblue{
-userId : Integer
-name : String
-status : boolean
+getId() : int
+getName() : String
+getStatus() : Boolean
}


GetListUI ..> GetUserAccountAndStatusListController #blue
GetUserAccountAndStatusListController .> "dataManagement" DataManagement #blue
GetUserAccountAndStatusListController .> UserStore #blue
GetUserAccountAndStatusListController -> UserMapper #blue
DataManagement *- UserStore #blue
UserStore *-- User #blue
UserMapper -> UserDTO #blue
UserDTO .. User #blue


@enduml