@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include DEVICONS/react.puml
!include DEVICONS/java.puml
!include DEVICONS/msql_server.puml
!include FONTAWESOME/users.puml


'######################
'######################

'LAYOUT_WITH_LEGEND()


'TITLE ON TOP
title Level 1: System Context diagram

'HEADER FOOTER DESCRIPTIONS
center header C4 MODEL
center footer C4 MODEL

'###################### end config
'######################

Person(user, "Customer", "People that need to use Project Management System", $sprite="users")
System(pms, "PMS \n Project Management System", "Allow client manage all projects in one application")

Rel(user, pms, "Manage all", "https")

@enduml