@startuml
'https://plantuml.com/sequence-diagram

autonumber
Actor "Project Manager" as actor

actor -> System: starts project information editing by entering the project code
actor <-- System: shows current information and asks what changes are to be made
actor -> System: introduces the changes to be made
actor <-- System: shows the changed data and informs of the operation success

@enduml