@startuml
'https://plantuml.com/class-diagram

title US025 SSD
skinparam sequenceMessageAlign center

autoactivate on
autonumber

actor "Administrator" as User
participant ":System" as System

activate User

User -> System: Starts activation of an account
System --> User: Request the user account ID
User -> System: Inserts the user account ID
System --> User: Return user account status
User -> System: Change user account status to "active"

System --> User: Changed status confirmation
@enduml