@startuml
'https://plantuml.com/class-diagram


autonumber
actor "Director" as director
participant ":CreateTypologyRoute(UI)" as route
participant "controllerTypology1:CreateTypologyController" as controller
participant "mapperTo:JsonToDTO" as mapperJson
participant "typologyCreationDTO"
participant "appServiceTypology1:AppServiceTypology" as service
participant "Description"
participant "TypologyID"
participant "typologyStore:TypologyStore" as repo
participant TypologyFactory
participant "typologyObjectCreated : Typology" as Typology
participant "typologyDTOObjectSaved : TypologyDTO ??? should it have a <OPTIONAL>" as typDTOObjectSaved


 director -> route :I want to create a Typology
 activate route
director <-- route: request data(description)
deactivate route
director -> route: insert data(description)
activate route

route -> controller: createTypology(json)
activate controller
controller -> controller:validate(json)
activate controller
deactivate controller
controller -> mapperJson: mapToDTOTypology(json)
activate mapperJson
mapperJson --> typologyCreationDTO**: create(json)
deactivate mapperJson


route -> controller: createTypology(typologyCreationDTO) ????
activate controller
controller -> controller:validate(typologyCreationDTO)  ???? é um If que valida se o DTO é null, empty e blank
activate controller
deactivate controller
controller -> service : createTypologyAndSave(typologyCreationDTO)



activate service
service -> typologyCreationDTO : description = getDescription()
service -> Description : typologyDescriptionVO = createDescription(description)
service -> TypologyID : typologyID = createTypologyID(typologyDescriptionVO)

service -> repo : doesTypologyExistByID(typologyID)  ???? Tenho de representar a alternativa ... isto é um IF

service -> TypologyFactory : createTypology(typologyID, typologyDescriptionVO)
TypologyFactory -> Typology**

service -> repo : save(typologyObjectCreated) : typologyObjectSaved
activate repo
repo -> repo : add(typologyObjectCreated)
repo -> repo : getTypologyByID(typology.getTypologyByID)
repo --> service: typologyObjectSaved : Typology
deactivate repo

service -> typDTOObjectSaved** : typologyDTOObjectSaved : TypologyDTO
typDTOObjectSaved -> Typology : getTypologyID()
typDTOObjectSaved -> Typology : getTypologyDescription()
typDTOObjectSaved --> service : typologyDTOObjectSaved : TypologyDTO


controller <-- service: Optional.of(typologyDTOObjectSaved) ???? should I represent it like this  ????
deactivate service
controller --> route :ResponseEntity.ok().body("Typology Created")  ????  should I represent it like this ??????
deactivate controller

director <-- route: ok



@enduml