@startuml
'https://plantuml.com/class-diagram

'TITLE ON TOP
title US011 - As Authenticated User, I want to change his/her password.

'HEADER FOOTER DESCRIPTIONS
center header ONION
center footer US011 - As Authenticated User, I want to change his/her password.

autoactivate on
autonumber

actor "User" as user
participant ":ChangeUserPassword(UI)" as route
participant ":ChangeUserPasswordController" as controller
participant "dtoAssembler:UserDomainDTOAssembler" as mapperJson
participant "userDTO1:UserDTO" as dtoUser1

participant ":ChangeUserPasswordService" as service
participant "userSaved:User" as user1

participant ":ChangeUserPasswordDomainService" as servicePassword

participant "userRepo1:UserRepository" as repo



user -> route :I want to change my password
user <-- route: request data(currentPassword, newPassword)
deactivate route
user -> route: insert data(currentPassword, newPassword)
route -> controller: ChangeUserPassword(changeUserPasswordDTO)
controller -> controller:validate(changeUserPasswordDTO)
deactivate controller
deactivate mapperJson
controller -> service : changeUSerPassword(changeUserPasswordDTO): userDTO1.1

service -> repo : getUserById(userId) : user
deactivate 

service -> USer : getCurrentPassword(userId) : user
deactivate

service -> servicePassword: setPassword(newPassword): userUpdated
servicePassword --> user1: setPassword(newPassword)

service -> mapperJson : mapToUserDTO(userUpdated):userDTO1.1
mapperJson -> user1 : getAttr():atr
mapperJson-> dtoUser1** : toDto(atr)
deactivate
deactivate mapperJson
deactivate user1
controller <-- service: userDTO1.1
deactivate service
route <-- controller : userDTO1.1
deactivate controller
user <-- route: ok
deactivate route

@enduml