@startuml

autonumber
autoactivate off



participant " profileRepository : ProfileRepository" as repo

participant " profileDomainDataAssembler : ProfileDomainDataAssembler" as assembler

participant " profile : Profile" as profile

participant "profileJPA : ProfileJPA" as profJPA

participant " profileRepositoryJPA : ProfileRepositoryJPA" as repoJPA

[-> repo: save(Profile)
activate repo

repo -> assembler : toData(profile)
activate assembler

assembler -> profile : profile.getProfileId()
activate profile
profile --> assembler : profileID

assembler -> profile : profile.getName()

profile --> assembler : profileName
deactivate profile

assembler --> profJPA **: create(profileID, profileName)

assembler --> repo : profileJPA
deactivate assembler

repo -> repoJPA : save(profileJPA)

repoJPA -> " profileSavedJPA : ProfileJPA" **: save(profileJPA)


repo -> assembler : toDomain(profileSavedJPA)
activate assembler

assembler -> profJPA : profileJPA.getID()
activate profJPA
profJPA --> assembler : profileID

assembler -> profJPA : profileJPA.getName()
profJPA --> assembler : profileName
deactivate profJPA


assembler --> " profileSaved : Profile " **: create( profileID, profileName )

assembler --> repo : profileSaved
deactivate assembler



[<- repo : profileSaved
deactivate repo



@enduml

