@startuml
'https://plantuml.com/class-diagram



 skinparam nodesep 80
 skinparam ranksep 80
left to right direction
 package UI{
 class AuthenticatedUserProjectsAllocatedUi{
 }
 }

 package switchisep.project{
 package Controller {
 class AuthenticatedUserProjectsAllocatedController{
 -dataManagement:DataManagement

 +getListOfProjectCodeByUserIdAllocated(userId, nowDate)

 }
 }

 package Model{
 class DataManagement{
 -projectStore:ProjectStore
 +getProjectStore()
 }

 class ProjectStore{

 + listOfProjectsUserIsAllocated()
 +add(projectCode)

 }

 class Project {

 getProjectTeam()
 getProjectManager()
 getScrumMaster()
 getProductOwner()

 }

 class ProjectTeam{

 getResources()

}
 }


 AuthenticatedUserProjectsAllocatedUi ..> AuthenticatedUserProjectsAllocatedController



 AuthenticatedUserProjectsAllocatedController .....> " dataManagement\n" DataManagement

 DataManagement "1" -- "1" ProjectStore

 AuthenticatedUserProjectsAllocatedController ..> "projectStore\n" ProjectStore

ProjectStore "1"-- "1..*"Project

Project "1"--"1..*" ProjectTeam


@enduml