@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor "AuthenticatedUser" as AuthenticatedUser
participant "System" as System

AuthenticatedUser -> System: I want to get a list of all projects I'm currently allocated to
activate System
AuthenticatedUser <-- System : Display listOfProjectsUserIsAllocated
deactivate System
@enduml