@startuml
'https://plantuml.com/class-diagram

'header
'Sequence Diagram of US030
'endheader

center footer SPRINT004 - Previous partial class diagram


class ProfileStore{
-profileList
+createAndAddProfile(profileName,permission)
}

class Profile{
   -profileID
   -profileName
   -permission

}


ProfileStore "1" o-- " profile 1..*" Profile


skinparam nodesep 140

skinparam ranksep 60

@enduml