@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor "SM/Team Member" as SM
participant ":System" as system

SM -> system: I want to register work done in a task
activate system
SM <-- system: request project code, user story ID, task ID, hour spent
deactivate system
SM -> system: input project code, user story ID, task ID, hour spent
activate system
SM <-- system:ok
deactivate system





@enduml