@startuml
'https://plantuml.com/class-diagram

Class CreateTaskUI

class CreateTaskController {
+getDataManagement()
+getListOfSprints(projCode)
+createTaskInSprint(taskName, taskDescription, taskType, startDate, endDate, effortEstimate)
}

class DataManagement{
+getProjectStore();

}

class ProjectStore{
-projectList : List<Project>
+getProjectByCode(projCode);
}

class Project{
}


class Sprint{
-sprintID : int
-description : String
-sprintOrder : Integer
-startDate : LocalDate
-endDate : LocalDate
-numberOfWeeks : Integer
-taskList : List<Task>
+getTaskList();
+getTasksStatus();
+CreateNewTask(taskName, taskDescription, taskType, startDate, endDate, effortEstimate)
}

class Task{
-taskName : String
-taskDescription : String
-taskStatus : String
-taskType : String
-startDate : LocalDate
-endDate : LocalDate
-effortEstimate : Integer
}

'class SprintDTO{
'-SprintID : Integer
'-numberOfWeeks : Integer
'-startDate : LocalDate
'-endDate : LocalDate
'-sprintOrder : Integer
'
'
'}

'class SprintMapper{
'-SprintToSprintDTO
'-listOfSprintDtoCreator
'}

CreateTaskUI -->   CreateTaskController

CreateTaskController --> " dataManagement" DataManagement

DataManagement --> " projectStore" ProjectStore

'CreateTaskController "1..*" ..down> "1..* sprintMapper" SprintMapper

'SprintMapper ..down> "1..* sprintDto" SprintDTO

'CreateTaskController ..> "sprintDto" SprintDTO

'SprintMapper ..down> "1..* sprint" Sprint

ProjectStore  --down> " project"  Project

Project  -down-> " sprint" Sprint

Sprint  --down> " task" Task



@enduml