@startuml
'https://plantuml.com/sequence-diagram



header
Sequence Diagram of US034
endheader

center footer US 034 - As Project Member, I want to update the status (i.e.: the Scrum Board category) of a user story in the scope of the current sprint backlog.


autoactivate on
autonumber


participant ":UserStoryMapper" as C7
participant "listOfListsDTO<List<UserStoryDTO>>:UserStoryDTO" as C15
participant "listUserStory : SprintBackLog" as C6
participant ":TaskMapper" as C8
participant "listTask:UserStory" as C9
participant ":Task" as C10
participant "listUserStoryDto : List<UserStoryDto>" as C13
participant "listTaskDto : List<taskDto>" as C11
participant "taskDto : TaskDto" as C12
participant "userStoryDto : UserStoryDto" as C14


[-> C7: toDto(listOfLists)

activate C7
C7 -> C15**:
loop [for each list]



C7 -> C13**: create()
loop [for each userStory]
C7 -> C6: us = getUs(i)
deactivate C6
C7 -> C6: usID = us.getUserStoryID()
deactivate C6

C7 -> C6: usStatus = us.getStatus()
deactivate C6

C7 -> C6: usDescription = showUserStoryDescription()
deactivate C6
'
'C7 -> C9: listTask = getTaskList()
'C7 <-- C9: listTask
'C8 -> C11**: create()
'loop [for each task]
'C7 -> C8: toDto(listTask)
'C8 -> C9: task = getTask(i)
'deactivate C9
'C8 -> C8: taskDto = toDto(task)
'C8 ->C12**: create(taskId, taskDescrition, startDate, endDate, taskStatus,effortEstimate, taskType)
'deactivate C8
'C8 -> C11: add(taskDto)
'deactivate C8
'deactivate C11
'end
'C7 -> C7: userStoryDto = toDto(userStory)
C7-> C14**: create(usID, usDescription, usStatus, parentID, effort, priority, listUserStoryDto)
C7 -> C13: add(userStoryDto)

end
C15 <- C13: add(listUserStoryDto)
deactivate C13
end
C7<--C15: listOfListsDTO

[<- C7: listOfListsDTO

@enduml