@startuml
'https://plantuml.com/class-diagram

autoactivate on
autonumber
actor "Non-registered user" as user
participant ":RegisterUserRoute(UI)" as route
participant ":RegisterUserController" as controller
participant "dtoAssembler:UserDomainDTOAssembler" as mapperJson
participant "userDTO:UserDTO" as dtoUser1
participant "user:User" as user1

participant ":RegisterUserService" as service

participant ":DefaultProfileDomainService" as serviceProfile

participant "userRepo1:UserRepository" as repo

participant "profileRepo1:ProfileRepository" as repoProfile




user -> route :I want to register myself
user <-- route: request data(name, email, function, password, photo)
deactivate route
user -> route: insert data(name, email, function, password, photo)
route -> controller: registerUser(json)
controller -> controller:validate(json)
deactivate controller
controller -> mapperJson: mapToUserDTO(json)
mapperJson --> dtoUser1**: create(json)
deactivate mapperJson
controller -> service : createUser(userDTO): userDTO1.1
service -> repoProfile : getProfileList() : profileList
service -> serviceProfile: getDefaultProfileID(profileList) : defaultProfileID
deactivate
deactivate
service --> user1**: createUser(userDTO)
service -> repo : save(user):userSaved
deactivate repo
service -> mapperJson : mapToUserDTO(userSaved):userDTO1.1


mapperJson -> user1 : getAttr():atr
deactivate mapperJson
deactivate user1
controller <-- service: userDTO1.1
deactivate service
route <-- controller : true
deactivate controller
user <-- route: ok
deactivate route


@enduml