@startuml
'https://plantuml.com/sequence-diagram

autonumber

Actor "Director" as actor

actor --> System: asks for list of project's human resources

System --> actor: returns list of project's human resources


@enduml