@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Team Member" as actor

actor -> System: wants to add a user story from the product backlog to the sprint backlog
actor <-- System:  requests the project code, the sprint ID and the user story ID
actor -> System: inserts the project code, the sprint ID and the user story ID
actor <-- System: informs of the operation success

@enduml