@startuml
'https://plantuml.com/sequence-diagram

autonumber

Actor Director_PO_PM_SM AS ACTOR

Participant UI
Participant ":ViewStatusOfActivitiesController" as ViewStatusOfActivitiesController
Participant ":DataManagement" as DataManagement
Participant "projectStore : ProjectStore" as ProjectStore
Participant "project : Project" as Project
Participant "activitiesStatusListOfLists"
Participant "activityStatusList"
Participant Activity
Participant "productBacklog : ProductBacklog" as ProductBacklog
Participant "tasksStatusListOfLists"
Participant "taskStatusList"
Participant UserStory
Participant Task

skinparam sequenceMessageAlign center
autonumber

activate ACTOR
activate UI
ACTOR -> UI: I want to view the status of activities in a project
UI --> ACTOR : Insert project code
ACTOR -> UI: Input: project code
activate ViewStatusOfActivitiesController
UI -> ViewStatusOfActivitiesController: viewActivitiesStatus(code)
deactivate UI
activate DataManagement
ViewStatusOfActivitiesController -> DataManagement : getProjectStore()
DataManagement --> ViewStatusOfActivitiesController : projectStore
deactivate DataManagement
activate ProjectStore
ViewStatusOfActivitiesController -> ProjectStore : getProjectByCode(code)
deactivate ProjectStore
ProjectStore -> Project : getActivitiesStatus()
activate Project
Project --> activitiesStatusListOfLists **: :List<List<String>>


loop For each Activty in Project
Project --> "activityStatusList" **: :List<String>

activate Activity
Project -> Activity : getActivityName()

activate "activityStatusList"
Activity --> "activityStatusList" : addActivityName
deactivate "activityStatusList"

Project -> Activity : getActivityDescription()

activate "activityStatusList"
Activity --> "activityStatusList" : addActivityDescription
deactivate "activityStatusList"

Project -> Activity : getActivityStatus()

activate "activityStatusList"
Activity --> "activityStatusList" : addActivityStatus
deactivate "activityStatusList"

deactivate Activity

"activityStatusList" --> activitiesStatusListOfLists : addActivityStatusList
activate activitiesStatusListOfLists
deactivate activitiesStatusListOfLists
end


Project --> ViewStatusOfActivitiesController : activitiesStatusListOfLists
deactivate ViewStatusOfActivitiesController

deactivate Project
activate UI
ViewStatusOfActivitiesController --> UI : activitiesStatusListOfLists
deactivate UI
UI --> ACTOR : Display: Table with project activities name, description and status

== ==

autonumber
activate UI
ACTOR -> UI: I want to view the status of activities in a project
UI --> ACTOR : Insert project code
ACTOR -> UI: Input: project code
deactivate UI
activate ViewStatusOfActivitiesController
UI -> ViewStatusOfActivitiesController: viewTasksStatus(code)
activate DataManagement
ViewStatusOfActivitiesController -> DataManagement : getProjectStore()
DataManagement --> ViewStatusOfActivitiesController : projectStore
deactivate DataManagement
activate ProjectStore
ViewStatusOfActivitiesController -> ProjectStore : getProjectByCode(code)
deactivate ProjectStore
deactivate ViewStatusOfActivitiesController
activate Project
ProjectStore -> Project : getProductBacklog()

Project -> ProductBacklog : viewTasksStatus()
deactivate Project

activate ProductBacklog
ProductBacklog --> "tasksStatusListOfLists" **: :List<List<String>>
loop For each UserStory in ProductBacklog
ProductBacklog --> "taskStatusList" **: :List<String>

loop For each Task in UserStory
activate Task
UserStory -> Task : getTaskName()
activate "taskStatusList"
Task --> "taskStatusList" : addTaskName
deactivate "taskStatusList"
UserStory -> Task : getTaskDescription()
activate "taskStatusList"
Task --> "taskStatusList" : addTaskDescription
deactivate "taskStatusList"
UserStory -> Task : getTaskStatus()
activate "taskStatusList"
Task --> "taskStatusList" : addTaskStatus
deactivate "taskStatusList"
deactivate Task
activate "tasksStatusListOfLists"
"taskStatusList" --> "tasksStatusListOfLists" : addTaskStatusList
deactivate "tasksStatusListOfLists"
end
end

ProductBacklog --> ViewStatusOfActivitiesController : tasksStatusListOfLists
deactivate ProductBacklog
activate ViewStatusOfActivitiesController
ViewStatusOfActivitiesController --> UI : tasksStatusListOfLists
deactivate ViewStatusOfActivitiesController
activate UI
UI --> ACTOR : Display: Table with project tasks name, description and status
deactivate UI

deactivate ACTOR

@enduml