@startuml
'https://plantuml.com/class-diagram

title US019 SSD
skinparam sequenceMessageAlign center

autoactivate on
autonumber

actor "Team Member" as User
participant ":System" as System

activate User

User -> System: Starts the association of effort estimate of a User Story
System --> User: request the project code
User -> System: Inserts the project code
System --> User: request the user story ID
User -> System: Inserts the user story ID
System --> User: request the effort estimate
User -> System: Inserts the effort estimate
System -> System: associate effort of a user story
System --> User: Effort estimate association done!
@enduml