@startuml
'https://plantuml.com/class-diagram

title US029 SSD
skinparam sequenceMessageAlign center

autoactivate on
autonumber

actor "ProjectManager" as User
participant ":System" as System

activate User

User -> System: I want to initialize a Sprint of a Project
System --> User: Requests to insert a projectCode
User -> System: Inserts the  ProjectCode
System --> User: Requests to insert a SprintID
User -> System: Inserts the SprintID
System --> User: Sprint Initiated Confirmation

@enduml