r5@startuml
'https://plantuml.com/class-diagram
hide members
'hide circle

skinparam minClassWidth 200
skinparam nodesep 80
skinparam ranksep 80
skinparam Padding 5
skinparam linetype ortho

'left to right direction

skinparam package  {
    BackgroundColor white
    BorderColor grey
    shadowing false
    FontStyle normal
    FontSize 16
    borderThickness 0.5
    fontColor #aaa
}

skinparam legend {
    backgroundColor white
    borderColor white
    shadowing false
    FontStyle normal
    FontSize 12
    borderThickness 0.5
    fontColor black
    Padding 20
    DesignedBorderColor white
}

skinparam class {
    stereotypeFontSize 10
    fontSize 16
    fontName Helvetica

    arrowColor black
    arrowThickness 1
    attributeIconSize 0

    borderColor black
    borderThickness 0.5
    backgroundColor #eee




}

skinparam entity {
    backgroundColor red
    borderColor black
    borderThickness 0.5
}

skinparam rectangle {
    shadowing false
    fontSize 15
    textAlignment left
    fontStyle italic
    stereotypeFontSize 10
    borderThickness 0.5

}

'TITLE ON TOP
title US003

'HEADER FOOTER DESCRIPTIONS
center header ONION
center footer DDD - Domain Driven Design


package Infrastructure #80FFFF {
class RequestProfileUI
}


package InterfaceAdapters #C0FFC0 {
    package Controllers{
        class ProfileRequestController
    }
    package Repositories #7ACff5{
        class UserRepository
        class ProfileRepository
        class ProfileRequestRepository

    }
}

package ApplicationServices_UseCaseServices #FFAFAF{
package AppServices{
class ProfileRequestService
}
package RepositoriesInterfaces{

interface IUserRepository
interface IProfileRepository
interface IProfileRequestRepository

}

}

package Entities_Core_Domain #FFE0C0{

package AggregateProfileRequest{
class ProfileRequest
}

}

RequestProfileUI -right-> ProfileRequestController
Infrastructure -[hidden]-> InterfaceAdapters
ProfileRequestRepository ..|> IProfileRequestRepository
InterfaceAdapters -[hidden]-> ApplicationServices_UseCaseServices
ApplicationServices_UseCaseServices -[hidden]->Entities_Core_Domain
ProfileRequestService .right.> IUserRepository
ProfileRequestService .left.> IProfileRepository
ProfileRequestService .left.> IProfileRequestRepository

UserRepository ..|> IUserRepository

ProfileRepository ..|> IProfileRepository


ProfileRequestController ..> ProfileRequestService

ProfileRequestService ..> ProfileRequest
'Profile .right.> User

@enduml