@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor Director

Director -> System: I want to define a project's product owner
Director <-- System: requests project code and User ID
Director -> System: inserts project code and user ID
Director <-- System: Defines the requested resource as the product owner of the requested project and informs of the operation success

@enduml