@startuml
'https://plantuml.com/use-case-diagram

left to right direction
:Director: as User
rectangle System{

    usecase "Select a project" as US1
    usecase "Find resource by user ID" as US2
    usecase "Define the resource found as the Product Owner of a project" as US3
}

User --> US1
User --> US2
User --> US3

@enduml