@startuml
'https://plantuml.com/class-diagram

header
Class Diagram of US034
endheader

center footer US 034 - As Project Member, I want to update the status (i.e.: the Scrum Board category) of a user story in the scope of the current sprint backlog.


package UI{
    class UpdateScrumBoardStatusUI
}
package core{
package Domain{

class DataManagement{

+getProjectStore()
}

class ProjectStore{

+getProject(projectCode)
}

class Project{

   -code
   -name
   -description
   -double budget
   -numberOfPlannedSprints
   -status
   -tartDate
   -endDate
   -defaultSprintDuration

    +getCurrentSprint()
    +setScrumBoardStatus(usID,newStatus)
}

class Sprint{
    -sprintID
    -sprintOrder
    -startDate;
    -endDate;
    -numberOfWeeks
    -sprintStatus;
+getSprintBackLog()
}

class SprintBackLog{
+setScrumBoardStatus(usID, newStatus)
}

class UserStory{
    -description
    -userStoryID
    -parentID
    -status
    -effort
    -priority
    -scrumBoardStatus
    +setScrumBoardStatus(newStatus)
}
}
package Controllers{
    class UpdateScrumBoardStatusController{
    +setScrumBoardStatus(projectCode,usID,newStatus)
    }
}
}
UpdateScrumBoardStatusUI ..> UpdateScrumBoardStatusController
UpdateScrumBoardStatusController ...>"dataManagement" DataManagement
DataManagement "1"-->"projectStore 1.*" ProjectStore
ProjectStore "1"*--" projectList 1.*" Project

UpdateScrumBoardStatusController ..> Project

Project "1"*-right-"sprintList  1..*" Sprint

Sprint "1"-right->"userStories 1" SprintBackLog

SprintBackLog "1"-right->"userStory 1..*" UserStory


skinparam nodesep 140

skinparam ranksep 60

@enduml