@startuml
'https://plantuml.com/class-diagram

hide members
hide circle
skinparam linetype ortho
skinparam minClassWidth 200
skinparam roundCorner 8
skinparam class {
    stereotypeFontSize 10
    fontSize 16
    fontName Helvetica

    arrowColor black
    arrowThickness 1
    attributeIconSize 0

    borderColor black
    borderThickness 0.5
    backgroundColor #eee


}


entity Project <<AGGREGATE ROOT>>
class ProjectCode <<VALUE OBJECT>>

entity Sprint <<AGGREGATE ROOT>>
class SprintID <<VALUE OBJECT>>


entity UserStory <<AGGREGATE ROOT>>
class UserStoryID <<VALUE OBJECT>>

entity Task <<AGGREGATE ROOT>>
class TaskID <<VALUE OBJECT>>

interface TaskContainerID <<INTERFACE>>



Project --> "1"ProjectCode

Sprint --> "1" SprintID
Sprint -up--> "1"ProjectCode


UserStory --> "1" UserStoryID
UserStory -up--> "1"ProjectCode
UserStory --> "0..*"SprintID

Task --> "1"TaskID
Task -up---> "1"ProjectCode

SprintID ..|> TaskContainerID
UserStoryID ..|> TaskContainerID
Task --> TaskContainerID



@enduml