@startuml
'https://plantuml.com/class-diagram

header
Sequence Diagram of US030
endheader

center footer DDD - Domain Driven Design



package project{
    entity Project <<AGGREGATE_ROUTE>>{
       -code
       -name
       -description
       -double budget
       -numberOfPlannedSprints
       -status
       -tartDate
       -endDate
       -defaultSprintDuration
    }

    entity ProductBacklog{

    }

    entity UserStory{
    private final int sprint;
        -description;
        -userStoryID;
        -parentID;
        -status
        -effort
        -priority
        -scrumBoardStatus
    }

    entity SprintBackLog{
    }

    entity Sprint{

        -sprintID
        -sprintOrder
        -startDate;
        -endDate;
        -numberOfWeeks
        -sprintStatus;
    }

     entity SprintList{
     }

     entity TaskInUS{
     }

     entity TaskInSprint{
     }

     entity ProjectCode <<VO>>{
     }

}

package User{
    entity User <<AGGREGATE_ROUTE>>{
    }

    class UserID <<VO>> {
    }

    class UserName <<VO>>{
    }

    class Status <<VO>>{
    }

    class Email <<VO>>{
    }

    class Function <<VO>>{
    }
    class Photo <<VO>>{
        }

}

package Profile{
    entity Profile <<AGGREGATE_ROUTE>>{
    }
    class ProfileName <<VO>>{
    }
    class Permission <<VO>>{
    }
}

package Typology{
    entity Typology <<AGGREGATE_ROUTE>>{
    }
    class TypologyName <<VO>>{
    }

}

package Resource{
      entity Resource <<AGGREGATE_ROUTE>>{
      }

      class startDate <<VO>>{
      }
      class endDate <<VO>>{
      }
      class costPerHour <<VO>>{
      }
      class percentageAllocation <<VO>>{
      }
      class role <<VO>>{
      }


}







Project "1"--"1" ProductBacklog
ProductBacklog "1"*--"0..*" UserStory
Project"1"--"1"SprintList
SprintList "1"*-down- "0..*" Sprint
Sprint -- "1"SprintBackLog
SprintBackLog o--"1..*" UserStory
UserStory  *--right-- "0..*" TaskInUS
Sprint "0..*"-right-*TaskInSprint
Project -right- ProjectCode

User -- UserID
User -right- UserName
User -- Status
User -- Email
User --Function
User -- Photo

Profile -- "1"ProfileName
Profile -- "1"Permission

Typology -- "1"TypologyName

Resource --> Project
Resource <-- User
Resource --> startDate
Resource --> endDate
Resource -- percentageAllocation
Resource -- role
Resource --> costPerHour

User -down- "1" Profile
Project -up-> Typology





'skinparam nodesep 140
'
'skinparam ranksep 60

@enduml