@startuml
skinparam nodesep 150
skinparam ranksep 250

left to right direction
class "Non registered user"
class Profile {
	-ProfileId
	-ProfileName
	-Permissions
}

class User {
	-User?d
	-Name
	-Function
	-Photo
	-Password
	-Email
	-Status
}

class Tasks {
	-Name
	-Description
	-Start date
	-End date
	-Hours spent
	-Effort estimate
	-Percentage of execution
	-Type
	-Status
	-Responsible
	-Task ID
}

class Typology {
	-Typology
}

class Resource {
	-Start date
	-End date
	-Cost per hour
	-Percentage allocation
	-Role
}

class Sprint {
	-StartDate
	-EndDate
	-Status
	-SprintID
	-SprintOrderNumber
	-SprintTasklist
}

class Project {
	-Code
	-Name
	-Description
	-Number of planned sprints
	-Status
	-Start date
	-End date
	-Budget
	-Sprint Default Duration
	-Sprint List
}

class "Sprint backlog"
class "User story" {
	-UserStoryID
	-Description
	-EffortEstimatte
	-Priority
	-User Story Status
}

class "Product Backlog"
class Customer {
	-Name
	-Business sector
	-Fiscal number
}


Project "1" -- "1..*" Sprint : <<creates and groups
"User story" "1" -- "1..*" "User story" : is decomposed in
User "1" -- "1..*" "User story" : product owner creates>
"Sprint backlog" -- "User story" : <<can be added to
User "1" -- "1..*" Typology : director create>
Typology "1" -- "1" Project : has 
Sprint -- "Sprint backlog" : has
Sprint "1" -- "1..*" Tasks : creates and stores
"User story" -- "1..*" Tasks : is decomposed in
"Product Backlog" "1" -- "1..*" "User story" : is composed by>
Project -- "Product Backlog" : has
Project -- Customer : is associated to
User "1" -- "1..*" Project : director create>
User "1" -- "1..*" Profile : administrator create and update
"Non registered user" ..> User : activation
"Non registered user" "1" -- User : register as
User "1" -- "1..*" Profile : request to administrator 
User "1..*" -- "1" Project : act as scrum master
User "1..*" -- "1" Project : act as product owner
User "1..*" -- "1" Project : act as project manager
Resource "1..*" -- "1" Project : is allocated to>
User "1..*" -- "1..*" Resource : is a
User "1" -- "1..*" Profile : is assigned to>
User "1" -- "1..*" Project : director allocate resources
User "1..*" -- "1..*" Project : project manager edit static information
Tasks "1..*" -- "1" User : execute
Project "1..*" -- "1..*" User : works on
@enduml