@startuml
'https://plantuml.com/class-diagram

'hide members
hide circle
'skinparam linetype ortho
skinparam minClassWidth 200
skinparam roundCorner 8
skinparam class {
    stereotypeFontSize 10
    fontSize 16
    fontName Helvetica

    arrowColor black
    arrowThickness 1

    borderColor black
    borderThickness 0.5
    backgroundColor #eee

}

Identifier <|.u. UserID
Identifier <|.u. ProfileID
Identifier <|.u. ProfileRequestID
Identifier <|.u. ResourceID
Identifier <|.u. ProjectID
Identifier <|.. SprintID
Identifier <|.. UserStoryID
Identifier <|.. TaskID
Identifier <|.. TypologyID

class Identifier <<Interface>> {
+ getId()
}

class UserID <<Value Object>> {
- String id
- Email email
+ getId()
}

class ProfileID <<Value Object>> {
- String id
- Name name
+ getId()
}

class ProfileRequestID <<Value Object>> {
- String id
- ProfileID profileID
- UserID userID
+ getId()
}

class ResourceID <<Value Object>> {
- String id
- UserID userID
- ProjectID projectID
- Timeperiod timePeriod
+ getId()
}

class ProjectID <<Value Object>> {
- String id
- Code code
+ getId()
}

class SprintID <<Value Object>> {
- String id
- ProjectID projectID
- Timeperiod timePeriod
+ getId()
}

class UserStoryID <<Value Object>> {
- String id
- ProjectID projectID
- Description description
+ getId()
}

class TaskID <<Value Object>> {
- String id
- TaskContainerID taskID
+ getId()
}

class TypologyID <<Value Object>> {
- String id
- Name name
+ getId()
}

@enduml