@startuml
'https://plantuml.com/class-diagram

package UI{
abstract class CreateTaskUI
}

package "Core"{
    package "Controllers" {

        class CreateTaskController {
        +createTaskInUserStory(code, sprintID, userStoryID, name, description, type): boolean
        }
        }
        CreateTaskUI ..|>  CreateTaskController

        package "Domain"{
        class DataManagement{
        -TypologyStore : typologyStore
        -UserStore : userStore
        -ProfileStore : profileStore
        -RoleStore : roleStore
        -ProfileRequestStore : profileRequestStore
        -ProjectStore projectStore
        -ResourceStore resourceStore
        -CustomerStore customerStore

        +getProjectStore();
        }

        class ProjectStore{
        -projectList : List<Project>
        +getProjectByCode(code);
        }

        class Project{
        -sprintList : List<Sprint>
        +getSprintByID(sprintID)
        }

        class Sprint{
        -sprintBacklog: SprintBacklog
        +getSprintBacklog()
        +validateSprintHasStarted()
        +createTaskInUserStory()
        }

        class SprintBacklog{
        -userStoryList: List<UserStory>
        getUserStoryByID(userStoryID)
        }

        class UserStory{
        -description : String
        -userStoryID : int
        -taskList : List<Task>
        +create(String name, String description, String type)
        +addTaskToUserStoryTaskList(task)
        }

        class Task{
        -taskName : String
        -taskDescription : String
        -taskStatus : String
        -taskType: String
        +validateTaskDates()
        }



        CreateTaskController ..|> "dataManagement\n" DataManagement
        CreateTaskController ..|> "projectStore\l" ProjectStore
        DataManagement "1" - "1" ProjectStore
        ProjectStore "1  " *-right-- "0..*" Project
        Project "1  " *--- "0..*" Sprint
        Sprint "1" --left- "1" SprintBacklog
        SprintBacklog "1  " *-left- "0..*" UserStory
        UserStory "1 " *-- "0..*" Task
        Sprint "1 " *-- "0..*" Task


skinparam nodesep 350

}
}
@enduml