@startuml
'https://plantuml.com/use-case-diagram

left to right direction
:Team Member: as User
package System{
    usecase "Insert project code" as US1
    usecase "Insert user story id" as US2
    usecase "Insert sprint id" as US3
    usecase "Insert task name, description, type, start date, end date" as US4
    usecase "Create new task in user story" as US5
    usecase "List of projects" as US6
    usecase "List of sprints" as US7
    usecase "List of user stories" as US8
}
User --> US1
User --> US2
User --> US3
User --> US4
User --> US5
US5 ..> US6 : include
US5 ..> US7 : include
US5 ..> US8 : include



@enduml