@startuml
'https://plantuml.com/class-diagram

skinparam maxMessageSize 300
autonumber
autoactivate on
actor "Product Owner" as po
participant ":CreateUSUI" as route
participant "controller\n:UserStoryController" as controller
participant "assembler\n: UserStoryDomainDTOAssembler" as assembler
participant "newUSInfo\n: NewUserStoryInfo" as newUSInfo

participant "usDTO \n: UserStoryDTO" as usDTO
participant "service \n: CreateUserStoryService" as service
participant "repository \n: UserStoryRepository" as repo



po -> route : I want to create a UserStory
po <-- route: Request UserStory Data
po -> route: Insert request data (description)
route -> controller:  createUserStory(description, projectCode)
controller -> assembler: toNewUserStoryInfo(description, projectCode)
assembler -->  newUSInfo ** : create
controller <-- assembler : newUserStoryInfo

controller -> service: createUserStory(newUserStoryInfo)

ref over service
US009_Application_Layer
end ref

service -> repo : save(userStory)

ref over repo
US009_Jpa
end ref

repo --> service: savedUserStory
assembler <- service: fromDomainToDTO(savedUserStory)

usDTO <-- assembler**:create

assembler -> service: userStoryDTO
deactivate assembler

service --> controller: Optional<UserStoryDTO>
deactivate service
controller -> controller : generateResponse(json)


controller --> route: response
deactivate controller

route --> po: UserStory successfully created







@enduml