@startuml
'https://plantuml.com/class-diagram

skinparam maxMessageSize 500
autonumber
autoactivate on
participant "service\n: CreateUserStoryService" as service
participant "repository\n: UserStoryRepository" as repo
participant "assembler \n: UserStoryDomainDTOAssembler" as assembler
participant "userStory \n: UserStory" as domainUS
participant "userStoryJpaRepository \n: UserStoryJpaRepository" as jpaRepo
participant "userStoryJPA \n: UserStoryJPA" as jpaUS
participant "savedUserStoryJpa \n: UserStoryJPA" as savedJpaUS
participant "savedUserStory \n: UserStory" as savedUS

activate service
service -> repo: savedUserStory(userStory)
repo -> assembler: toData(userStory)
assembler -> domainUS: getUserStoryAttributes()
domainUS --> assembler: userStoryAttributes
assembler --> jpaUS**: create(userStoryID, projectCode, description, parentUserStory, status, priority, effort)
assembler --> repo: userStoryJPA

repo -> jpaRepo: save( userStoryJPA )
jpaRepo -> savedJpaUS **: create
jpaRepo --> repo: savedUserStoryJpa

repo -> assembler: toDomain( savedUserStoryJPA)
assembler --> savedUS**: create
assembler --> repo: savedUserStory
repo --> service: savedUserStory







@enduml