@startuml
'https://plantuml.com/use-case-diagram

header
Use Case Diagram of US030
endheader

center footer US 030 - As Team Member, I want to view the Scrum Board of current sprint.



left to right direction
:Team member: as User
package System{
    usecase "Request the ScrumBoard List" as US1
    usecase "List of projects" as US6
    usecase "Insert project code" as US2
    usecase "Get ScrumBoard List" as US5
User --> US1
US1 ..> US6 : include
User --> US2
User --> US5

@enduml