@startuml
'https://plantuml.com/sequence-diagram

header
Sequence Diagram of US030
endheader

center footer US 030 - As Team Member, I want to view the Scrum Board of current sprint.



autoactivate on
autonumber

actor "Team member" as User
participant ":ScrumBoardViewUI" as UI
participant ":ScrumBoardViewController" as Controller
participant ":Datamanagement" as C1
participant "projectStore : ProjectStore" as C2
participant "p :Project" as C3
participant ":UserStoryMapper" as C7
participant "sprint :Sprint" as C4
participant "listUserStory :SprintBacklog" as C8

'participant ":UserStory" as C12
'participant "listOfLists<List<UserStory>>:UserStory" as C13
'participant "listUSToDo<UserStory>:UserStory" as C9
'participant "listUSInProgress<UserStory>:UserStory" as C10
'participant "listUSDone<UserStory>:UserStory" as C11


activate User

User -> UI: Starts ScrumBoard view feature
User <-- UI: request the project code
User -> UI:  indicates the project Code
UI -> Controller: getListsForScrumBoard(projectCode)
Controller -> C1: projectStore = getProjectStore()
Controller <-- C1: sendProjectStore
Controller -> C2: p = getProjectByCode(projectCode)
Controller <-- C2: p
Controller -> C3: getListsForScrumBoard()

C3 -> C4: getListsForScrumBoard()
C4 -> C8: getListsForScrumBoard()
ref over C8
US030-SD_ListsForScrumBoard
end

'deactivate C4
'
'C8 -> C13**: create()
'C8 -> C9**: create()
'C8 -> C10**: create()
'C8 -> C11**: create()
'loop [for each userStory]
'    alt     userStory.getScrumBoardStatus = ToDo
'        C8 -> C9: add(us)
'    else
'    alt userStory.getScrumBoardStatus = inProgress
'            C8 -> C10: add(us)
'        else
'            C8 ->C11: add(us)
'        end
'    end
'end
'C9 -> C13: add(listUSInProgress<User>)
'deactivate C9
'C10 -> C13: add(listUSInProgress<User>)
'deactivate C10
'C11 -> C13: add(listUSInProgress<User>)
'deactivate C9
'deactivate C11
'
'deactivate C4

'deactivate C13
'deactivate C13


C4 <-- C8: listOfLists
C3 <-- C4: listOfLists


Controller <-- C3: listOfLists

Controller -> C7:listsToDto(listOfLists)
ref over C7
SD_ScrumBoardMapper_List
end ref

Controller<-- C7: scrumBoardDTO
UI <-- Controller: scrumBoardDTO
User <-- UI: scrumBoardDTO
@enduml