@startuml
'https://plantuml.com/class-diagram

'######################
'######################  start config
skinparam linetype ortho
hide members
'hide circle

skinparam minClassWidth 200
skinparam nodesep 80
skinparam ranksep 20
skinparam padding 3

skinparam package  {
    BackgroundColor white
    BorderColor grey
    shadowing false
    FontStyle normal
    FontSize 16
    borderThickness 0.5
    fontColor #000
}

skinparam legend {
    backgroundColor white
    borderColor white
    shadowing false
    FontStyle normal
    FontSize 12
    borderThickness 0.5
    fontColor black
    padding 0
    DesignedBorderColor white
}

skinparam class {
    stereotypeFontSize 10
    fontSize 20
    fontName Helvetica

    arrowColor black
    arrowThickness 1
    attributeIconSize 0

    borderColor black
    borderThickness 0.5
    backgroundColor #eee


}

skinparam entity {
    backgroundColor red
    borderColor black
    borderThickness 0.5

}

skinparam rectangle {
    shadowing false
    fontSize 15
    textAlignment left
    fontStyle italic
    stereotypeFontSize 10
    borderThickness 0.5

}

'TITLE ON TOP
title US009 - As Product Owner, I want to create a user story and add it to the Product Backlog.


'HEADER FOOTER DESCRIPTIONS
center header ONION
center footer DDD - Domain Driven Design

'###################### end config
'######################

rectangle "Interface Adapters" #C0FFC050  {

      rectangle "Controllers" #C0FFC080  {

          package "ImplementedControllers" #7acff5  {

            class CreateUserStoryController

          }

          package "Repositories" #7acff5  {

            class UserStoryStore

          }

      }

}

rectangle "Application Services / Use Case Services" #FFAFAF50  {

rectangle "App Services" #FFAFAF80  {

          package "InterfaceAppServices" #7acff5  {

            interface ICreateProjectAppService
            interface IProjectFactory

          }

          package "ImplementedAppServices" #7acff5  {

            class CreateProjectAppService
            class ProjectFactory

          }

          package "InterfaceRepositories" #7acff5  {

            interface IUserStoryStore

          }

      }

}

rectangle "Entities / Core / Domain" #FFE0C050  {

    rectangle "Aggregates" #7acff580  {

        package "Project" <<Aggregate>> #7acff5  {

            class Project <<Root>>

        }

        package "Typology" <<Aggregate>> #7acff5  {

            class Typology <<Root>>
        }
    }

    package "Services" #7acff5  {

    }

    package "ValueObjects" #7acff5 {

        class ProjectID <<Value Object>>
        class TypologyID <<Value Object>>
        class ProjectCode <<Value Object>>



    }
}




CreateProjectAppService .left.> IProjectFactory

CreateUserStoryController .down.> ICreateProjectAppService



CreateProjectAppService ..up.|> ICreateProjectAppService


IProjectFactory .l.|> ProjectFactory

UserStoryStore .down.|> IUserStoryStore

CreateProjectAppService ...right.> IUserStoryStore

CreateProjectAppService ...down.> Project

Project ...> TypologyID
Typology ...> TypologyID
Project ...> ProjectID
Project ...> ProjectCode


@enduml