@startuml
'https://plantuml.com/class-diagram


RefineUserStoryUI .. RefineUserStoryController
RefineUserStoryController --->"dataManagement" DataManagement
DataManagement "1"-->"projectList 1" ProjectStore
ProjectStore *---right---" project 1.*" Project

RefineUserStoryController ..> ProductBacklog
RefineUserStoryController ..> ProjectStore
RefineUserStoryController ..> Project

ProductBacklog o---"user story 0.*" UserStory
Project "1"*---"productBackLog  1" ProductBacklog
class RefineUserStoryUI {

}

class RefineUserStoryController {
-ProjectStore

+getProjectStore()
+getProjectProductBackLog(projectCode)
+refineUserStory(fatherUserStoryID, newUserStoryDescription: List<String>)
}

class DataManagement{}

class ProjectStore{
-ResourceStore

+getProjectProductBackLog(projectCode)
}

class Project{
-ProductBacklog
}

class ProductBacklog{


+create (fatherUserStoryId, description)
}

skinparam nodesep 120

skinparam ranksep 40


@enduml