@startuml
'https://plantuml.com/class-diagram
hide circle
skinparam classAttributeIconSize 0
hide methods

title Domain Model extract

class Project {
    -code
    -name
    -description
    -number of planned sprints
    -status
    -Start date
    -end date
    -budget
    -sprint duration
}

class ProductBacklog {
    -List: UserStorys
}

class UserStory {
    -ID
    -description
    -fatherUsId
    -priority
}

Project "1" -right-> "1" ProductBacklog: has
ProductBacklog "1" -> "1..*" UserStory: is composed by


@enduml