@startuml
'https://plantuml.com/sequence-diagram

title Sequence Diagram of US020

autoactivate on
autonumber

actor "Product Owner" as User
participant ":RefineUserStroryUI" as UI
participant ":RefineUserStroryController" as Controller
participant ":Datamanagement" as C1
participant "projectStore : ProjectStore" as C2
participant "p : ProjectStore" as C3
participant "productBacklog : ProductBacklog" as C4
participant ":UserStory" as C5



activate User

User -> UI: Starts the refine UserStory feature
User <-- UI: request the project code
User -> UI:  indicates the project Code
UI -> Controller: getProjectProductBackLog(projectCode)
Controller -> C1: projectStore=getProjectStore()
Controller <-- C1: sendProjectStore
Controller -> C2: p = getProjectByCode(projectCode)
Controller <-- C2: p
Controller -> C3: getProductBackLog()
Controller <-- C3: productBacklog
UI <-- Controller: productBacklog
User <-- UI: Show productBacklog

User -> UI: Indicates the User Story to Refine
UI -> Controller: refineUserStory(fatherUserStoryID, newUserStoryDescription:List<String>)
Controller -> C4: refineUserStory(fatherUserStoryID, newUserStoryDescription:List<String>)
loop [for each list description]

C4 -> C5**: create(fatherUserStoryId, description)
C4 -> C4: validate(userStory)
C4 -> C4: add(userStory)
end
Controller <-- C4: ok
UI <-- Controller: ok
User <-- UI: ok


@enduml