@startuml
'https://plantuml.com/class-diagram

@startuml
'https://plantuml.com/class-diagram
hide empty members

class CreateUserStoryUI

class CreateUserStoryController{
    dataManagement
    getProjectListByRoleId(roleId)
    getProjectByRoleId(projectCode, roleId)
    createUserStory(projectCode, description)
    addUserStory(projectCode, userStory)
    }

class DataManagement{
    getProjectStore()
}

class ProjectStore{
    List<Project>: projectList
    getProjectListByRoleId(roleId)
}

class Project{
        String: code
        String: name
        String: description
        double: budget
        Typology: typology
        ProductBacklog: productBacklog
        Customer: customer
        int: numberOfPlannedSprints
        String: status
        ProjectTeam: projectTeam
        LocalDate: startDate
        LocalDate: endDate
        List<Activity>: activityList
        List<Sprint>: sprintList
    getProductBacklog()
}

class ProductBacklog{
    List<UserStory>: userStoryList
    createUserStory(description)
    addUserStory(userStory)
}

class UserStory {
    String: description
}

CreateUserStoryUI ..|>  CreateUserStoryController
CreateUserStoryController -- "uses" DataManagement
CreateUserStoryController ..|>  "gets" ProjectStore
DataManagement -- ProjectStore
ProjectStore -r- Project
Project "1" o-- "has" ProductBacklog
ProductBacklog  "1" o-- "is composed by"UserStory


@enduml