@startuml
'https://plantuml.com/class-diagram

GetProfileListUI ..|> GetProfilesListController
GetProfilesListController -|> ProjectStore : Get list
GetProfilesListController -|> DataManagement : Get



class GetProfileListUI {
Request projects list
}

class GetProfilesListController {
Request projects list
}

class DataManagement {
+ getProjectStore()
}

class ProjectStore {
+ getProjectList()
}


@enduml