@startuml
'https://plantuml.com/class-diagram

'######################
'######################  start config
skinparam linetype ortho
hide members
'hide circle

skinparam minClassWidth 200
skinparam nodesep 80
skinparam ranksep 20
skinparam padding 3

skinparam package  {
    BackgroundColor white
    BorderColor grey
    shadowing false
    FontStyle normal
    FontSize 16
    borderThickness 0.5
    fontColor #000
}

skinparam legend {
    backgroundColor white
    borderColor white
    shadowing false
    FontStyle normal
    FontSize 12
    borderThickness 0.5
    fontColor black
    padding 0
    DesignedBorderColor white
}

skinparam class {
    stereotypeFontSize 10
    fontSize 20
    fontName Helvetica

    arrowColor black
    arrowThickness 1
    attributeIconSize 0

    borderColor black
    borderThickness 0.5
    backgroundColor #eee


}

skinparam entity {
    backgroundColor red
    borderColor black
    borderThickness 0.5

}

skinparam rectangle {
    shadowing false
    fontSize 15
    textAlignment left
    fontStyle italic
    stereotypeFontSize 10
    borderThickness 0.5

}


'HEADER FOOTER DESCRIPTIONS
center header ONION
center footer DDD - Domain Driven Design

'###################### end config
'######################


rectangle Infrastructure #80FFFF50  {


    package Routes #7acff5 {

        class CreateProfileRoute



    }
    package "Pesistence" #7acff5  {

                interface ProfileJPARepository

                interface CrudRepository

              }


}


rectangle "Interface Adapters" #C0FFC050  {



      rectangle "Controllers" #C0FFC080  {



          package "ImplementedControllers" #7acff5  {

            class CreateProfileController



          }

          package "Repositories" #7acff5  {

            class ProfileRepository

          }

      }

}

rectangle "Application Services / Use Case Services" #FFAFAF50  {

rectangle "App Services" #FFAFAF80  {



          package "ImplementedAppServices" #7acff5  {

            class CreateProfileService


          }

          package "InterfaceRepositories" #7acff5  {

            interface ProfileRepositoryInterface


          }

      }

}



CreateProfileRoute ....down.> CreateProfileController


CreateProfileController ..> CreateProfileService

ProfileRepository .down..|> ProfileRepositoryInterface


CreateProfileService ...left.> ProfileRepositoryInterface




ProfileRepository ..> ProfileJPARepository
ProfileJPARepository --right----|> "extends" CrudRepository


@enduml