@startuml
'https://plantuml.com/sequence-diagram
header
Sequence Diagram of US029
endheader

center footer US029 - As Project Manager, I want to start a sprint of current sprint.



autoactivate on
autonumber

actor "Project Manager" as User
participant "StartSprintUI" as UI
participant ":InitiateSprintController" as Controller
participant ":DataManagement" as C2
participant "projectStore : ProjectStore" as C3
participant "projectA :Project" as C4
participant "sprintA :Sprint" as C5

activate User


User -> UI: I want to initialize a Sprint of a Project
UI --> User: Requests to insert a projectCode
User -> UI: Inserts the  ProjectCode
UI --> User: Requests to insert a SprintID
User -> UI: Inserts the SprintID
UI -> Controller: startASprint(sprintIDNumber, nowDate, projectCode)
Controller -> C2: projectStore = getProjectStore()
deactivate C2
Controller -> C3:  projectA = getProjectByCode(projectCode)
deactivate C3
Controller -> C4:  startASprint(sprintID,nowDate)


C4 -> C4: validateIfThereAreStartedSprintsStatus()
deactivate C4
C4 -> C4: validateSprintDatesAreOutOfProjectDates(nowDate)
deactivate C4
C4 -> C4: periodsOverlappingDetectionExceptOneSprint(int sprintID, LocalDate newSprintStartDate)
deactivate C4

    C4 -> C4: sprintA = getSprintBySprintID(sprintID)
    deactivate C4

    C4 -> C5: setSprintNewStartDate(nowDate)
C5 -> C5: setStartDate(nowDate)
deactivate C5
C5 -> C5: setEndDate(endDate)
deactivate C5
C5 -> C5: setSprintStatusToStarted()
deactivate C5
C4 <-- C5: return True
Controller <-- C4: return True
UI <-- Controller: return True
User <-- UI: Sprint Initiated Confirmation

@enduml