@startuml
'https://plantuml.com/sequence-diagram

autonumber

Participant ":ProfileStore" as ProfileStore
Participant "profileFactory :ProfileFactory" as pfi
Participant "profile :Profile" as Profile

--> ProfileStore: createAndAddProfile(String profileName, \n int permissions, profileFactoryInterface)
ProfileStore --> ProfileStore: validateNewProfileName(String profileName)
ProfileStore --> ProfileStore: returnNextProfileId()
ProfileStore --> pfi: createProfile(int id,\n String profileName, int permissions)
pfi --> Profile** :
pfi --> ProfileStore: profile
ProfileStore --> ProfileStore: add(profile)

<-- ProfileStore: true


@enduml