@startuml
'https://plantuml.com/class-diagram

header
Sequence Diagram of US012
endheader

center footer US 012 - As Director, I want to create Typology.

package userInterface{
class CreateTypologyUserInterface
}

package controller{
class CreateTypologyController{
+createTypology(String description)
}
}

package model{
class DataManagement{
+getTypologyStore()
}
class TypologyStore {
-List<Typology> typologyList
+getTypologyList()
#checkIfTypologyIsDuplicated(Typology)
+addTypology(Typology)
}

class Typology {
-String description
#checkRulesForTypologyCreation()
}
}


CreateTypologyUserInterface .down-|> CreateTypologyController

DataManagement <|-up. CreateTypologyController
DataManagement --> TypologyStore
Typology <-up- TypologyStore






@enduml