@startuml
'https://plantuml.com/class-diagram

title US012 SSD
skinparam sequenceMessageAlign center

autoactivate on
autonumber

actor "Director" as User
participant ":System" as System

activate User

User -> System: Starts the creation of new project typology
System --> User: request the description of the  typology
User -> System: Inserts the new Typology
System -> System: Create new typology
System --> User: Creation of new typology done!
@enduml