@startuml
'https://plantuml.com/sequence-diagram


autonumber
autoactivate on

actor Director
Participant ": CreateTypologyUserInterface"
Participant ": CreateTypologyController" as TypCtrl
Participant ": DataManagement" as dataManagement
Participant ": TypologyStore" as TypStr
Participant ": Typology" as typ


Director -> ": CreateTypologyUserInterface": Start the creation of new typology
": CreateTypologyUserInterface" --> Director: Request description of the new Typology

Director -> ": CreateTypologyUserInterface": Inserts description of the new Typology


": CreateTypologyUserInterface" -> TypCtrl: createTypology(description)
TypCtrl -> dataManagement: typologyStore = getTypologyStore()
dataManagement --> TypCtrl: typologyStore
TypCtrl -> TypStr: createTypology((description)

TypStr -> typ ** : createTypology(description)
activate typ

typ -> typ : checkRulesForTypologyCreation(description))
deactivate

typ -> TypStr: typology
TypStr -> TypStr : checkIfTypologyIsDuplicated(typology)
TypStr -> TypStr : addTypology(typology)
TypStr --> TypCtrl : ok
TypCtrl --> ": CreateTypologyUserInterface" : ok
": CreateTypologyUserInterface" --> Director : ok







@enduml