@startuml
'https://plantuml.com/sequence-diagram


skinparam monochrome true

title SD of the US021
center header
Sequence Diagram
I want to associate a human resource (user) to a project.
endheader
center footer SWitCH

autoactivate on
autonumber

Actor ProductOwner AS ACTOR
Participant ": UpdateProjectProductBacklogUI" AS UI
Participant ": UpdateProjectProductBacklogController" AS CONTROLLER
Participant ": DataManagement" AS DM
Participant ": ProjectStore" AS PS
Participant ": Project" AS P
Participant ": ProductBacklog" AS PB

ACTOR -> UI : Request Product Backlog By Project Code
UI -> CONTROLLER : :requestProductBacklogByProjectCode(projectCode)
CONTROLLER -> DM : :getProjectByProjectCode(projectCode)
CONTROLLER <-- DM : projectStore

CONTROLLER -> PS : :getProductBacklogByProjectCode(project)
PS -> P : :getProductBack(project)
P -> PB : :getUserStoriesList(project)
P <-- PB : projectProductBacklog
PS <-- P : projectProductBacklog
CONTROLLER <-- PS : projectProductBacklog
UI <-- CONTROLLER : projectProductBacklog
ACTOR <-- UI : projectProductBacklog

ACTOR -> UI : Request User Story Priority (oldIndex, newIndex)
UI -> CONTROLLER : requestUserStoryPriority(oldIndex, newIndex)
CONTROLLER -> PB : updateUserStoryPriority(oldIndex, newIndex)
CONTROLLER <-- PB : true
UI <-- CONTROLLER : true
ACTOR <-- UI : update successful

@enduml