@startuml
'https://plantuml.com/sequence-diagram

skinparam monochrome true

title SSD of the US021
center header
System Sequence Diagram
As Product Owner, I want to change the priority of a user story in the product backlog.
endheader
center footer SWitCH

autoactivate on
autonumber

actor "Product Owner" as User
participant ":System" as System

activate User

User -> System: Request Product Backlog By Project Code (projectCode)
System --> User: Show Project Product Backlog

User -> System: Request User Story Priority (oldIndex, newIndex)
System --> User: Update successful

@enduml