@startuml
'https://plantuml.com/sequence-diagram

header
Sequence Diagram of US030
endheader

center footer US 030 - As Team Member, I want to view the Scrum Board of current sprint.



autoactivate on
autonumber

participant "listUserStory :SprintBacklog" as C8
participant ":UserStory" as C12
participant "listOfLists<List<UserStory>>:UserStory" as C13
participant "listUSToDo<UserStory>:UserStory" as C9
participant "listUSInProgress<UserStory>:UserStory" as C10
participant "listUSDone<UserStory>:UserStory" as C11


[-> C8: getListsForScrumBoard()




C8 -> C13**: create()
C8 -> C9**: create()
C8 -> C10**: create()
C8 -> C11**: create()
loop for each userStory
    alt     userStory.getScrumBoardStatus = ToDo
        C8 -> C9: add(us)
    else
    alt userStory.getScrumBoardStatus = inProgress
            C8 -> C10: add(us)
        else
            C8 ->C11: add(us)
        end
    end
end
C9 -> C13: add(listUSInProgress<User>)
deactivate C9
C10 -> C13: add(listUSInProgress<User>)
deactivate C10
C11 -> C13: add(listUSInProgress<User>)
deactivate C9
deactivate C11

C8 <-- C13: listOfLists
deactivate C13
deactivate C13


[<- C8: listOfLists

@enduml