@startuml
'https://plantuml.com/sequence-diagram

title SSD of the US030

autoactivate on
autonumber

actor "Team Member" as User
participant ":System" as System

activate User

User -> System: Starts the Scrum Board Viewing
System --> User: request the project code
User -> System: Inserts the project code
System -> System: get the Lists for ScrumBoard
System --> User: show Lists for ScrumBoard

@enduml