@startuml
'https://plantuml.com/sequence-diagram

title SD_ScrumBoardMapper

header
Sequence Diagram of US030
endheader

center footer US 030 - As Team Member, I want to view the Scrum Board of current sprint.


autoactivate on
autonumber


participant ":ScrumBoardDTOMapper" as C7
participant ":UserStoryMapper" as C6
participant "scrumBoardDTO : ScrumBoardDTO" as C14


[-> C7: toDto(listOfLists)
Activate C7

C7 -> C7: listToDo = listOflists.get(0)
C7 -> C6: userStoryDTOList(listTodo)
ref over C6
US030-SD_UserStoryMapper_toDTO
end
C7 <-- C6: toDoListDTO
deactivate C7

C7 -> C7: listInProgress = listOflists.get(1)

C7 -> C6: userStoryDTOList(listInProgress)

ref over C6
US030-SD_UserStoryMapper_toDTO
end
C7 <-- C6: inProgressListDTO
deactivate C7
C7 -> C7: listDone = listOflists.get(1)
C7 -> C6: userStoryDTOList(listDone)
ref over C6
US030-SD_UserStoryMapper_toDTO
end
C7 <-- C6: doneListDTO
deactivate C7

C7--> C14**: create(toDoListDTO, inProgressListDTO,doneListDTO)

[<- C7: ScrumBoardDTO

@enduml