@startuml
'https://plantuml.com/sequence-diagram

title SD_UserStoryMapper_toDTO

header
Sequence Diagram of US030
endheader

center footer US 030 - As Team Member, I want to view the Scrum Board of current sprint.


autoactivate on
autonumber


participant ":UserStoryMapper" as C7
participant "listUserStory : SprintBackLog" as C6
participant "listUserStoryDto : List<UserStoryDto>" as C13
participant "userStoryDto : UserStoryDto" as C14


[-> C7: userStoryDTOList(list)

activate C7
C7 -> C13**: create()
loop for each userStory
C7 -> C6: us = getUs(i)
deactivate C6
C7 -> C6: usID = us.getUserStoryID()
deactivate C6

C7 -> C6: usStatus = us.getStatus()
deactivate C6

C7 -> C6: usDescription = showUserStoryDescription()
deactivate C6

C7-> C14**: create(usID, usDescription, usStatus, parentID, effort, priority, listUserStoryDto)
C7 -> C13: add(userStoryDto)


deactivate C13
end

[<- C7: listDTO

@enduml