@startuml
'https://plantuml.com/class-diagram
hide circle
skinparam classAttributeIconSize 0
hide methods

title Domain Model extract

class Profile {
    -ProfileID
    -ProfileName
    -Permissions
}

class User {
    -UserID
    -Name
    -Function
    -Photo
    -Password
    -Email
    -Status
}

User "1" -left- "1..*" Profile: is assigned to
User "1" -right- "1..*" Profile: request to administrator >
User "1" -down- "     1..*" Profile: administrator create and update >


skinparam nodesep 110
@enduml
