@startuml
'https://plantuml.com/sequence-diagram

title User Story 09 - System Sequence Diagram

autonumber
Actor "Product Owner" as actor
Participant ":System" as System

activate actor

actor -> System : Get list of projects based on PO Id
System --> actor : Show available projects
actor -> System : Select project
System --> actor : Return selected project
actor -> System : Start a new User Story
System --> actor : Request User story description
actor -> System: Insert requested data
System --> actor: Shows data and requests confirmation
actor -> System: Confirms the data
System --> actor: Informs Success
@enduml