@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor AuthenticatedUser as AuthenticatedUser
participant ":AuthenticatedUserProjectsAllocatedUi" as AuthenticatedUserProjectsAllocatedUi
participant ":AuthenticatedUserProjectsAllocatedController" as AuthenticatedUserProjectsAllocatedController
participant ":DataManagement" as DataManagement
participant "projectStore:ProjectStore" as ProjectStore

activate AuthenticatedUser
AuthenticatedUser -> AuthenticatedUserProjectsAllocatedUi: I want to get a list of all projects I'm currently allocated to
activate AuthenticatedUserProjectsAllocatedUi
AuthenticatedUserProjectsAllocatedUi -> AuthenticatedUserProjectsAllocatedController: getListOfProjectCodeByUserIdAllocated(userId, nowDate)
activate AuthenticatedUserProjectsAllocatedController
AuthenticatedUserProjectsAllocatedController -> DataManagement: getProjectStore():projectStore
activate DataManagement
AuthenticatedUserProjectsAllocatedController <-- DataManagement: projectStore
deactivate DataManagement
AuthenticatedUserProjectsAllocatedController -> ProjectStore :projectStore.getListOfProjectCodeByUserIdAllocated(userId, nowDate)
activate ProjectStore
ProjectStore --> listOfProjectsUserIsAllocated **: :List<String>
activate listOfProjectsUserIsAllocated
loop for each project

ProjectStore -> ProjectStore : validate if user is allocated

ProjectStore -> listOfProjectsUserIsAllocated: add(projectCode)

end

ProjectStore<-- listOfProjectsUserIsAllocated:listOfProjectsUserIsAllocated
deactivate listOfProjectsUserIsAllocated
AuthenticatedUserProjectsAllocatedController <-- ProjectStore :listOfProjectsUserIsAllocated
deactivate ProjectStore
AuthenticatedUserProjectsAllocatedUi <-- AuthenticatedUserProjectsAllocatedController: listOfProjectsUserIsAllocated
deactivate AuthenticatedUserProjectsAllocatedController
AuthenticatedUser <-- AuthenticatedUserProjectsAllocatedUi: display listOfProjectsUserIsAllocated
deactivate AuthenticatedUserProjectsAllocatedUi

@enduml