@startuml
'https://plantuml.com/class-diagram

'' ////////////////////
'' SET GLOBAL VARIABLES
!$TITLE  = "US005 - As Director, I want to register/create a new project. \n SECTION :: HATEOAS Hypermedia links creation"
!$SUB_TITLE = "ONION ARCHITECTURE"
'' END SET GLOBAL VARIABLES
'' ////////////////////

'' ///////////////////
'' // SET PARTICIPANTS

participant ": ProjectController" as controller
participant ": CreateProjectService" as service

'' // END SET PARTICIPANTS
'' ///////////////////////

'' ////////////////
'' // SET SEQUENCE

|||
autonumber


activate controller

controller <-- service : optionalProjectDTO




deactivate controller

|||
'' // END SET SEQUENCE
'' ///////////////////

'' ////////////////
'' THEME AND STYLES

''TITLE ON TOP
title $TITLE
''HEADER FOOTER DESCRIPTIONS
center header $SUB_TITLE
center footer $SUB_TITLE \n SWitCH

''STYLES
'skinparam monochrome true
skinparam maxMessageSize 500
skinparam roundCorner 4
autonumber

skinparam sequence {


    ActorBorderColor #111
    ActorBackgroundColor #eee
    ActorBorderThickness 0.8
    ActorFontColor black
    ActorFontSize 15
    'ActorFontName Helvetica

    ParticipantPadding 10
    ParticipantBorderColor #666
    ParticipantBackgroundColor lightblue
    ParticipantBorderThickness 0.8
    'ParticipantFontName Helvetica
    ParticipantFontSize 15
    ParticipantFontColor black

    ArrowColor black
    ArrowThickness 0.8
    ArrowFontSize 15

    'LifeLineBorderColor #666
    'LifeLineBorderColor #438DD5
    LifeLineBorderColor #1168BD
    LifeLineBackgroundColor white

    ReferenceBorderThickness  0.8
    ReferenceFontSize 16

}

skinparam note {
    borderColor #666
    backgroundColor #fde52e
    'borderColor yellow
    borderThickness 0.8
}

'' END THEME AND STYLES
'' ////////////////




@enduml